This is makeindex, version 2.17 [TeX Live 2026/dev] (kpathsea + Thai support).
Scanning style file ./diplomka.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file diplomka.acn....done (90 entries accepted, 0 rejected).
Sorting entries....done (623 comparisons).
Generating output file diplomka.acr....done (71 lines written, 0 warnings).
Output written in diplomka.acr.
Transcript written in diplomka.alg.
